@startuml abort_sequences
actor Client
participant ClientInterface
participant PaymentGateway
participant Robot

Client -> ClientInterface: new order
ClientInterface -> PaymentGateway: //prepare// (order)
note right 
card rejected
end note
PaymentGateway --> ClientInterface: //abort// (order_id)

ClientInterface --> Client: order rejected

Client -> ClientInterface: new order
ClientInterface -> PaymentGateway: //prepare// (order)
PaymentGateway --> ClientInterface: //ready// (order_id)
ClientInterface -> Robot: //prepare// (order)
note right
ran out of a 
flavor stock
end note
Robot --> ClientInterface: //abort// (order_id)
ClientInterface -> PaymentGateway: //abort// (order_id)
ClientInterface --> Client: order rejected

@enduml