@startuml happy_sequence
actor Client
participant ClientInterface
participant PaymentGateway
participant Robot

Client -> ClientInterface: new order
ClientInterface -> PaymentGateway: //prepare// (order)
PaymentGateway --> ClientInterface: //ready// (order_id)
ClientInterface -> Robot: //prepare// (order)
Robot --> ClientInterface: //ready// (order_id)
ClientInterface -> PaymentGateway: //commit// (order)
PaymentGateway --> ClientInterface: //finished// (order_id)
ClientInterface -> Robot: //commit// (order)
Robot --> ClientInterface: //finished// (order_id)
ClientInterface --> Client: order ready

@enduml